### PR TITLE
scannerview: Add textbox to enter roll.no manually

### LINKED ISSUE #56: Add feature to Enter Roll number manually
If the barcode scanner fails to read the barcode or if the barcode is not visible then in that case give the user functionality to enter the roll number manually

### PR DESCRIPTION
**Pull request by satyam372**
image
Fixes #56

### CODE REVIEW

File: lib/views/scannerview.dart [hunk 1]
```diff
@@ -18,6 +19,7 @@ class ScanScreenState extends State<ScanScreen> {
   String? _barcode;
   bool visible = false;
   late InsertData _insertData;
+  final TextEditingController _barcodeController = TextEditingController();
```
Comment (satyam372) [inline lib/views/scannerview.dart:23]: TextEditingController To handle the roll.no entered by student

File: lib/views/scannerview.dart [hunk 2]
```diff
@@ -141,11 +139,33 @@ class ScanScreenState extends State<ScanScreen> {
...
+                    ),
+                    textCapitalization: TextCapitalization.characters,
+                  ),
+                ),
+                const SizedBox(height: 20),
+                ElevatedButton(
+                  onPressed: () {
+                    if (_barcodeController.text.isNotEmpty) {
+                      String barcode = _barcodeController.text.replaceAll(RegExp(r'\s+'), '');
+                      _startBarcodeScan(barcode);
```
Comment (satyam372) [inline lib/views/scannerview.dart:163]: This handles the case where we can have an space in a Text (roll.no)
